apiVersion: v1
kind: ConfigMap
metadata:
  name: flag-service-config
  namespace: togglemaster
data:
  DB_HOST: "togglemaster-rds-flag.cazcgm4ikzel.us-east-1.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "postgres"
  PORT: "8000"