apiVersion: v1
kind: Secret
metadata:
  name: flag-service-secret
  namespace: togglemaster
type: Opaque
data:
  DB_USER: "ZmxhZ19hZG1pbg=="      # ex: flag_admin em base64
  DB_PASSWORD: "YTxoOiF4JGh4eTpZaFhJejw8eDB8Y1Q3cS16JA=="