apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: togglemaster
  labels:
    app: analytics-service
spec:
  replicas: 1 # Geralmente começa com 1 e escala via HPA/KEDA conforme a fila enche
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
      - name: analytics-service
        image: "271384503138.dkr.ecr.REGIAO.amazonaws.com/togglemaster/analytics-service:latest"
        envFrom:
        - configMapRef:
            name: analytics-service-config
        # Descomente a linha abaixo apenas se estiver usando as chaves de Conta Pessoal
        # - secretRef:
        #     name: analytics-service-secret
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "300m"
            memory: "256Mi"