apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: togglemaster
data:
  # Cole aqui o Endpoint gerado pelo RDS (ex: togglemaster-rds-auth.c123.us-east-1.rds.amazonaws.com)
  DB_HOST: "togglemaster-rds-auth.cazcgm4ikzel.us-east-1.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "postgres"
  PORT: "8080" # Porta padrão comum para APIs em Go