apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: togglemaster
type: Opaque
data:
  # Gere o base64 do usuário administrador do banco (ex: auth_admin)
  DB_USER: "YXV0aF9hZG1pbg=="
  # Gere o base64 da senha que você definiu na criação do RDS
  DB_PASSWORD: "RzRmTypIaWUtXV9QNTxOM08/dz82LUQ1dVBXVg=="