apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: togglemaster
spec:
  type: ClusterIP # Tipo exigido pelo enunciado do Tech Challenge
  selector:
    app: auth-service
  ports:
  - protocol: TCP
    port: 8080       # Porta do Serviço
    targetPort: 8080 # Porta exposta pelo contêiner Go