apiVersion: v1
kind: Secret
metadata:
  name: targeting-service-secret
  namespace: togglemaster
type: Opaque
data:
  DB_USER: "dGFyZ2V0aW5nX2FkbWluecho"      # ex: targeting_admin em base64
  DB_PASSWORD: "KndDZDdvRGtvT2VSTTpwaShZMy5DdjJNPHQjQQ=="