apiVersion: v1
kind: ConfigMap
metadata:
  name: evaluation-service-config
  namespace: togglemaster
data:
  REDIS_HOST: "PREENCHER_ENDPOINT_PRIMARIO_REDIS"
  REDIS_PORT: "6379"
  SQS_QUEUE_URL: "https://sqs.us-east-1.amazonaws.com/271384503138/MyQueue"
  PORT: "8080"